/* eslint-disable @next/next/no-html-link-for-pages -- vinext cannot hydrate next/link on this route. */
const cliCommands = [
  ["Discover", "actui discover . --json"],
  ["Start", "actui run --workflow ci.yml --event pull_request --json"],
  ["Wait", "actui wait <run-id> --after-cursor 12 --json"],
  ["Failures", "actui logs <run-id> --failed --json"],
  ["Cancel", "actui cancel <run-id> --json"],
];

export default function DocsPage() {
  return (
    <main className="docs-shell">
      <header className="docs-topbar">
        <a className="brand" href="/"><span className="brand-mark" aria-hidden="true"><i /><i /></span><span>Act<span>UI</span></span></a>
        <nav aria-label="Documentation"><a href="#start">Start</a><a href="#agents">Agents</a><a href="#protocol">Protocol</a><a href="#safety">Safety</a></nav>
        <a className="secondary-button" href="/">Open dashboard</a>
      </header>
      <div className="docs-layout">
        <aside className="docs-nav"><p>Handbook</p><a href="#start">Quick start</a><a href="#dashboard">Dashboard</a><a href="#cli">CLI and JSON</a><a href="#agents">Coding agents</a><a href="#mcp">MCP server</a><a href="#protocol">Event protocol</a><a href="#safety">Trust and safety</a><a href="#act">Act compatibility</a><a href="#license">Attribution</a></aside>
        <article className="docs-content">
          <div className="docs-hero"><p className="eyebrow">ActUI handbook</p><h1>One local CI run.<br />Humans and agents together.</h1><p>ActUI is a shared workbench around <a href="https://github.com/nektos/act">nektos/act</a>. The dashboard, JSON CLI, and MCP tools all observe and control the same run manager.</p></div>

          <section id="start"><span className="doc-number">01</span><div><h2>Quick start</h2><p>Build ActUI once, then launch it from the repository whose workflows you want to inspect.</p><pre><code>npm install{`\n`}npm run build{`\n`}npm link{`\n`}actui /path/to/repo --trust</code></pre><p>ActUI binds to loopback, chooses an available port, opens one browser tab, and writes a private session descriptor to your operating system cache. Without <code>--trust</code>, the dashboard remains safely read-only.</p><div className="doc-callout"><strong>Prerequisites</strong><span>Node.js 22+, Docker Engine or Docker Desktop, and a compatible <code>act</code> executable on PATH.</span></div><h3>When Act is missing</h3><p>Request a run normally. ActUI detects macOS, Windows, or Linux and presents the appropriate copyable installation command. Run it, verify with <code>act --version</code>, then restart ActUI. When Act is already installed outside PATH, use <code>actui . --act-path /absolute/path/to/act --trust</code>.</p><ul><li>macOS: <code>brew install act</code></li><li>Windows: <code>winget install nektos.act</code></li><li>Linux: use Act’s official pre-built installer shown in the dashboard.</li></ul><p><a href="https://nektosact.com/installation/index.html" target="_blank" rel="noreferrer">Open the official Act installation guide ↗</a></p></div></section>

          <section id="dashboard"><span className="doc-number">02</span><div><h2>The visual workbench</h2><p>Workflows, Run history, and Environment are independent dashboard views with bookmarkable URL hashes. Press <code>Command-K</code> on macOS or <code>Control-K</code> elsewhere—or select the repository switcher—to open the command palette and move between them.</p><h3>Workflows and repository job lists</h3><p>Every job contains its own ordered steps, so the execution hierarchy stays legible while selecting a run scope. Select individual jobs, enter a list name, and choose <strong>Save list</strong>. ActUI stores lists and the last active list locally under the repository’s absolute path; reopening that repository restores its list automatically, while another repository receives independent presets.</p><h3>Run history and full-viewport console</h3><p>The Run history view lists every retained run separately from workflow configuration. Within its console, every job is a tab whose panel collects only that job’s ordered step states and attributed logs. Process-level Act messages appear once under <strong>Run output</strong>; they are not repeated in every job. Choose <strong>Full viewport</strong> to dedicate the browser viewport to the console; choose <strong>Exit full view</strong> or press <code>Escape</code> to return.</p><h3>Environment</h3><p>The Environment view reports Act, Docker, repository path, and session trust, and links directly to runner settings or Act installation help when needed.</p><ul><li>Dependency-blocked jobs stay visibly waiting until their prerequisites finish.</li><li>Every local run has a durable status, cursor, audit trail, initiator, and optional agent session.</li><li>Cancellation from the browser and agent interfaces reaches the same Act process.</li><li>Run history and job-list preferences remain local to the machine.</li></ul></div></section>

          <section id="cli"><span className="doc-number">03</span><div><h2>Provider-neutral CLI</h2><p>Every automation command emits structured JSON and connects to the currently running ActUI session.</p><div className="command-table">{cliCommands.map(([label, command]) => <div key={label}><strong>{label}</strong><code>{command}</code></div>)}</div><p>Use <code>--workflow</code> more than once to run several workflow files. Protected jobs additionally require <code>--approved</code>. Cursor waits are bounded at 30 seconds so an agent can remain responsive.</p></div></section>

          <section id="agents"><span className="doc-number">04</span><div><h2>Agent test-and-fix loop</h2><p>The bundled <code>actui-test-and-fix</code> skill teaches coding agents a deliberately narrow loop:</p><ol><li>Discover workflows and choose the smallest relevant scope.</li><li>Start a run and surface its dashboard URL to the human.</li><li>Wait for concise changes after the last cursor.</li><li>Inspect only failed steps and selected log ranges.</li><li>Change files only when the user authorized a fix.</li><li>Rerun only the failed job or workflow, stopping on success, a blocker, or the attempt limit.</li></ol><pre><code>actui install-skill</code></pre><p>The dashboard displays the agent’s phase, attempt number, changed files, notes, and initiator so its activity is legible while it works.</p></div></section>

          <section id="mcp"><span className="doc-number">05</span><div><h2>Local MCP server</h2><p>Start the stdio server with <code>actui mcp</code>. It prints a readiness message and then remains open while it waits for an MCP client; it is a protocol server, not an interactive shell. Configure a provider-neutral client with command <code>actui</code> and arguments <code>[&quot;mcp&quot;]</code>, and keep <code>actui . --trust</code> running in another terminal for workflow discovery and execution.</p><div className="doc-callout"><strong>Clean protocol output</strong><span>Readiness and setup guidance are written to stderr. Stdout remains reserved for MCP JSON-RPC messages, so the terminal help cannot interfere with a connected client.</span></div><p>It exposes these tools:</p><div className="tool-cloud"><code>discover_workflows</code><code>start_run</code><code>wait_for_run</code><code>get_run</code><code>get_failed_steps</code><code>read_logs</code><code>cancel_run</code><code>rerun_failed</code><code>open_dashboard</code></div><p>The MCP server is a thin client of the local HTTP control plane. It never creates an independent execution state.</p></div></section>

          <section id="protocol"><span className="doc-number">06</span><div><h2>Open cursor protocol</h2><p>Each material change increments a run cursor. Browser clients use SSE snapshots; agents use bounded <code>changes</code> requests to receive only what happened since their last cursor.</p><pre><code>{`GET /api/runs/{runId}/changes?after=12&timeout=25000\n\n{\n  "runId": "…",\n  "afterCursor": 12,\n  "cursor": 15,\n  "changes": [\n    { "cursor": 14, "type": "logs.available",\n      "logRange": { "from": 30, "to": 44, "count": 15 } },\n    { "cursor": 15, "type": "run.failure", "status": "failure" }\n  ]\n}`}</code></pre><p>Live log bursts are compacted into one addressable range. Failed-step results include workflow, job, step when derivable, exit code, summary, source annotation, log range, and latest cursor.</p></div></section>

          <section id="safety"><span className="doc-number">07</span><div><h2>Trust and safety</h2><div className="safety-grid"><div><strong>Trusted repository gate</strong><p>Workflow execution is disabled unless the launch command includes <code>--trust</code>.</p></div><div><strong>Protected jobs</strong><p>Deploy, publish, release, production, privileged, and similar jobs require explicit per-run approval.</p></div><div><strong>Local secrets</strong><p>Profiles are private plaintext <code>.env</code> files outside the checkout. Values are never returned by the API; agent runs require explicit approval, and per-run files are deleted after execution.</p></div><div><strong>Bounded loops</strong><p>Agent reruns stop at the configured attempt limit. Every note, run, cancellation, and result enters the audit trail.</p></div></div></div></section>

          <section id="act"><span className="doc-number">08</span><div><h2>Act compatibility</h2><p>ActUI delegates workflow planning and execution to Act through its documented CLI. It supports event payloads, job and matrix filters, runner mappings, concurrency, offline mode, artifacts, environment variables, repository variables, and secret files. Local execution can differ from GitHub-hosted runners, especially for runner images and unsupported platform features.</p><h3>Custom runner labels</h3><p>Act skips unknown labels such as <code>ubuntu-latest-low</code> unless they are mapped with <code>-P</code>. ActUI detects selected jobs with unsupported labels before execution, suggests a compatible mapping such as <code>ubuntu-latest-low=catthehacker/ubuntu:act-latest</code>, and passes multiple configured mappings as repeated platform arguments. Review image trust and compatibility before pulling it. See the <a href="https://nektosact.com/usage/runners.html" target="_blank" rel="noreferrer">official Act runner guide ↗</a>.</p></div></section>

          <section id="license"><span className="doc-number">09</span><div><h2>Attribution</h2><p>ActUI uses <a href="https://github.com/nektos/act">nektos/act</a> as its local GitHub Actions execution engine. Act is an independent project distributed under the MIT License. ActUI preserves Act’s copyright and license notice in <code>THIRD_PARTY_NOTICES.md</code>.</p><p>ActUI itself is released under the MIT License. Product names and trademarks belong to their respective owners.</p></div></section>
        </article>
      </div>
    </main>
  );
}
